### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by DIDONEproject** [johentsch/ms3#6]
Error produced while parsing all the scores in a folder.
Commands executed:
> p = ms3.Parse("name of the folder", key = 'all')
> p.parse_mscx()

```
ERROR   Did25M-Va_lusingando-1730-Sarro[2.17][0159] -- parse.py (line 639) _parse():
        Traceback (most recent call last):
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 632, in _parse
            score = Score(path, read_only=read_only, logger_name=self.logger.name, level=level)
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\score.py", line 125, in __init__
            self._parse_mscx(mscx_src, read_only=read_only)
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\score.py", line 195, in _parse_mscx
            self._mscx = MSCX(self.full_paths['mscx'], read_only=read_only, parser=self.parser, logger_name=ln)
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\score.py", line 376, in __init__
            self.parse_mscx()
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\score.py", line 387, in parse_mscx
            self._parsed = _MSCX_bs4(self.mscx_src, read_only=self.read_only, logger_name=self.logger.name)
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\bs4_parser.py", line 59, in __init__
            self.parse_measures()
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\bs4_parser.py", line 89, in parse_measures
            self.parse_mscx()
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\bs4_parser.py", line 69, in parse_mscx
            self.soup = bs4.BeautifulSoup(file.read(), 'xml')
          File "C:\Users\user\AppData\Local\Programs\Python36\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 40076: character maps to <undefined>
```

And finally:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 494, in parse_mscx
    self.collect_annotations_objects_references(ids=ids)
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 154, in collect_annotations_objects_references
    if 'annotations' in score._annotations:
AttributeError: 'NoneType' object has no attribute '_annotations'
```
> p

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 900, in __repr__
    return self.info(return_str=True)
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 438, in info
    detached = sum(True for id in parsed_ids if self._parsed_mscx[id].has_detached_annotations)
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 438, in <genexpr>
    detached = sum(True for id in parsed_ids if self._parsed_mscx[id].has_detached_annotations)
AttributeError: 'NoneType' object has no attribute 'has_detached_annotations'
```

> p.parsed

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 62, in parsed
    return {k: score.full_paths['mscx'] for k, score in self._parsed_mscx.items()}
  File "C:\Users\user\AppData\Local\Programs\Python36\lib\site-packages\ms3\parse.py", line 62, in <dictcomp>
    return {k: score.full_paths['mscx'] for k, score in self._parsed_mscx.items()}
AttributeError: 'NoneType' object has no attribute 'full_paths'
```

**Comment by johentsch** [comment]
Could you please see whether the error persists with v0.4.1?

**Comment by DIDONEproject** [comment]
With this new version we obtain the expected output!: 123/124 MSCX files have been parsed. 👍 
Nevertheless, we have a cruised score, the same that was triggering the error in the last issue, which says: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 40076: character maps to <undefined>
